import React from 'react';
import { Route } from 'react-router';
 
export default (
    <Route>
          <Route path="/super-bowl/"/>
          <Route path="/about-us/" />
          <Route path="/posts/"  /> 
          <Route path="/contact-us/" /> 
          <Route path="/locations/" />
          <Route path="/limousine-service/" />
          <Route path="/corporate-transportation" />
          <Route path="/wedding-transportation/" />
          <Route path="/airport-car-service/"  />
          <Route path="/wine-tour/" />
          <Route path="/Transportation-coordinator/" />
          <Route path="/church-limo/" />
          <Route path="/casino-trips/"/>
          <Route path="/party-limo/" />
          <Route path="/bachelor-party/" />
          <Route path="/bachelorette-party/" />
          <Route path="/graduation-limo/" />
          <Route path="/concert-limo/" />
          <Route path="/locations/atlanta/" />
          <Route path="/locations/atlanta-car-service/" />
          <Route path="/locations/atlanta-limousine/" />
          <Route path="/locations/atlanta-party-bus/" />
          <Route path="/locations/los-angeles/"/>
          <Route path="/locations/los-angeles-car-service/" />
          <Route path="/locations/los-angeles-limousine/" />
          <Route path="/locations/los-angeles-party-bus/" />
          <Route path="/locations/houston/" />
          <Route path="/locations/houston-car-service/" />
          <Route path="/locations/houston-limousine/" />
          <Route path="/locations/houston-party-bus/" />
          <Route path="/locations/san-francisco/" />
          <Route path="/locations/san-francisco-car-service/" />
          <Route path="/locations/san-francisco-limousine/" />
          <Route path="/locations/san-francisco-party-bus/"/>
          <Route path="/locations/new-york/" />
          <Route path="/locations/new-york-car-service/"/>
          <Route path="/locations/new-york-limousine/" />
          <Route path="/locations/new-york-party-bus/" />
          <Route path="/locations/savannah/" />
          <Route path="/locations/savannah-car-service/" />
          <Route path="/locations/savannah-limousine/" />
          <Route path="/locations/savannah-party-bus/" />
          <Route path="/locations/jacksonville/" />
          <Route path="/locations/jacksonville-car-service/" />
          <Route path="/locations/jacksonville-limousine/" />
          <Route path="/locations/jacksonville-party-bus/" />
          <Route path="/dallas-car-service/" />
          <Route path="/nashville-car-service-nashville-bna-airport/" />
          <Route path="/phoenix-car-service-phx-airport/"/>
          <Route path="/locations/macon/" />
          <Route path="/locations/macon-car-service/"  />
          <Route path="/locations/macon-limousine/"  />
          <Route path="/locations/macon-party-bus/"  />
          <Route path="/locations/augusta/" />
          <Route path="/locations/augusta-car-service/" />
          <Route path="/locations/augusta-limousine/"  />
          <Route path="/locations/augusta-party-bus/"  />
          <Route path="/locations/chicago/"  />
          <Route path="/locations/chicago-car-service/" />
          <Route path="/locations/chicago-limousine/"  />
          <Route path="/locations/chicago-party-bus/"  />
          <Route path="/locations/miami/"  />
          <Route path="/locations/miami-car-service/" />
          <Route path="/locations/miami-limousine/"  />
          <Route path="/locations/miami-party-bus/"/>
          <Route path="/locations/orlando/"  />
          <Route path="/locations/orlando-car-service/" />
          <Route path="/locations/orlando-limousine/"  />
          <Route path="/locations/orlando-party-bus/" />
          <Route path="/locations/palm-beach/"  />
          <Route path="/locations/palm-beach/"  />
          <Route path="/locations/palm-beach-limousine/"  />
          <Route path="/locations/palm-beach-party-bus/" />
          <Route path="/locations/destin/" />
          <Route path="/locations/destin-car-service/" />
          <Route path="/locations/destin-limousine/"  />
          <Route path="/locations/destin-party-bus/"  />
          <Route path="/locations/columbus/"  />
          <Route path="/locations/columbus-car-service/" />
          <Route path="/locations/gray/"  />
          <Route path="/locations/gray-car-service/"  />
          <Route path="/locations/gray-limousine/"  />
          <Route path="/locations/kentucky-car-service/"  />
          <Route path="/alpharetta-car-service-atlanta-atl-airport/"  />
          <Route path="/athens-car-service-atlanta-atl-airport/" />
          <Route path="/car-service-atlanta-airport/"  />
          <Route path="/auburn-car-service/"  />
          <Route path="/buford-car-service/" />
          <Route path="/Austin-car-service/"  />
          <Route path="/buckhead-car-service-atlanta-atl-airport/"  />
          <Route path="/cordele-car-service-atlanta-atl-airport/"  />
          <Route path="/corpus-christi-car-service/"/>
          <Route path="/dublin-car-service-atlanta-atl/"  />
          <Route path="/dunwoody-car-service-atlanta-atl-airport-limousine/" />
          <Route path="/car-service-elp-el-paso-airport/" />
          <Route path="/flowery-branch-car-service-atlanta-atl/"  />
          <Route path="/garland-car-service-dallas-fort-worth-dfw/" />
          <Route path="/Hiram-car-service/" />
          <Route path="/jonesboro-car-service-atlanta-atl-airport-limousine/"/>
          <Route path="/marietta-car-service-atlanta-atl-airport/" />
          <Route path="/naples-car-service-southwest-rsw/" />
          <Route path="/the-woodlands-car-service/"/>
          <Route path="/tomball-car-service/"  />
          <Route path="/tuscaloosa-car-service-birmingham-bhm/"  />
          <Route path="/hampton-car-service-atlanta-atl-airport/" />
          <Route path="/west-university-place-car-service-houston/"  />
          <Route path="/charlotte-car-service-charlotte-clt-airport/"  />
          <Route path="/tips-for-fast-and-easy-departures-airport-car-service/" />
          <Route path="/benefits-of-an-airport-car-service/"/>
          <Route path="/warner-robins-car-service/" />
          <Route path="/atlanta-hartsfield-jackson-airport/" />
          <Route path="/chauffeur/"  />
          <Route path="/atlanta-hawks-limo/"/>
          <Route path="/valdosta-car-service/" />
          <Route path="/houston-sprinter-shuttle-services/" />
          <Route path="/best-airport-car-service-deal-in-houston-tx/" />
          <Route path="/san-antonio-airport-car-service-san-antonio-grand-limousine-corporate-transportation/"/>
          <Route path="/houston-executive-shuttle-service/" />
          <Route path="/augusta-golf-transportation/"  />
          <Route path="/no-more-mistakes-with-san-francisco-limousine-service/"  />
          <Route path="/carolina-panthers-football-limo-service/"  />
          <Route path="/greater-houston/"  />
          <Route path="/404/"/>
          <Route path="/galveston-car-service-houston-iah-airport/" />
          <Route path="/river-oaks-car-service-houston-iah-airport/"  />
          <Route path="/league-city-car-service-houston-iah-airport/"  />
          <Route path="/greater-heights-car-service-houston-iah/" />
          <Route path="/arlington-airport-car-service/" />
          <Route path="/dallas-car-service-dallas-fort-worth-dfw/"  />
          <Route path="/summer-travel-tips-usa/"  />
          <Route path="/the-masters-tournament/"  />
          <Route path="/atlanta-bachelorette-party-limo/" />
          <Route path="/new-york-city-travel-tours/" />

    </Route>
);